version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 3004:3004
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: martinmarinov
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5434
volumes:
  db-data:
