name: Basic CI pipeline

on:
  push:
    branches:
    - main

jobs:
  install_dependencies:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Run eslint
      run: npm run lint
    - name: Run unit test
      run: npm run test

