# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
    - main

jobs:
  install_dependencies:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: npm install
      
  build:
    runs-on: macos-latest
    steps:
    - name: Build project
      run: npm run build
      
  lint:
    runs-on: macos-latest
    steps:
    - name: Run eslint
      run: npm run lint
